-- Bring the current storefront catalogue into the admin-managed product table.
-- Safe to re-run: existing product slugs and product images are left in place.
with seed(slug, name, department, subcategory, price_bdt, compare_at_bdt, description, sku, materials, swatches) as (
  values
    ('marlow-table-lamp','Marlow Table Lamp','lamps','table-lamps',420, null,'A sculptural ceramic base and softly tapered shade bring a warm, quiet glow to bedside tables and reading corners.','CL-MARLOW','["Ceramic","Linen","Brass"]'::jsonb,'[{"label":"Brushed Brass","color":"#C9A362"},{"label":"Ivory","color":"#E8E0D4"}]'::jsonb),
    ('solis-pendant','Solis Dome Pendant','lamps','pendant-lights',680, null,'A generous spun-metal shade casts focused, welcoming light over kitchen islands and dining tables.','CL-SOLIS','["Brass","Metal"]'::jsonb,'[{"label":"Warm Brass","color":"#C9A362"},{"label":"Chalk","color":"#F0EBE0"}]'::jsonb),
    ('oslo-side-table','Oslo Side Table','tables','side-tables',540, null,'A compact oak table with a rounded top, sized for a favourite lamp, a book, and a cup of tea.','CL-OSLO','["Oak Wood"]'::jsonb,'[{"label":"Natural Oak","color":"#C8A96E"},{"label":"Smoked Oak","color":"#6B4B32"}]'::jsonb),
    ('cleo-wall-sconce','Cleo Wall Sconce','lamps','wall-lights',360, null,'A petite brass wall light with a softly diffused glow for hallways, bedside reading, and layered lighting.','CL-CLEO','["Brass"]'::jsonb,'[{"label":"Brushed Brass","color":"#C9A362"},{"label":"Matte Black","color":"#3A3530"}]'::jsonb),
    ('milo-console-table','Milo Console Table','tables','console-tables',920, null,'A slim oak console creates a considered landing spot for keys, a mirror, and a small accent lamp.','CL-MILO','["Oak Wood"]'::jsonb,'[{"label":"Natural Oak","color":"#C8A96E"},{"label":"Walnut","color":"#6B4B32"}]'::jsonb),
    ('iris-dining-table','Iris Dining Table','tables','dining-tables',1550,1800,'A clean-lined solid ash table with room for shared meals, good conversation, and a beautiful pendant overhead.','CL-IRIS','["Natural Ash","Walnut"]'::jsonb,'[{"label":"Natural Ash","color":"#D4B896"},{"label":"Walnut","color":"#6B4B32"}]'::jsonb),
    ('nora-table-lamp','Nora Glass Table Lamp','lamps','table-lamps',480, null,'Clear, hand-finished glass and a linen shade create an airy accent that works from desk to bedside.','CL-NORA','["Glass","Linen"]'::jsonb,'[{"label":"Clear Glass","color":"#E8E0D4"},{"label":"Smoked Glass","color":"#6B7A8D"}]'::jsonb),
    ('arc-floor-lamp','Arc Floor Lamp','lamps','floor-lamps',1150, null,'A slender arched stem and generous linen shade bring warm, adjustable light beside a reading nook.','CL-ARC','["Marble","Linen","Metal"]'::jsonb,'[{"label":"Travertine & Linen","color":"#E8E0D4"},{"label":"Marble & Charcoal","color":"#3A3530"}]'::jsonb),
    ('solene-wall-mirror','Solene Arched Wall Mirror','mirrors','wall-mirrors',680, null,'A softly arched mirror framed in warm brushed brass, made to brighten an entryway or dressing space.','CL-SOLENE','["Glass","Brass"]'::jsonb,'[{"label":"Brushed Brass","color":"#C9A362"},{"label":"Matte Black","color":"#3A3530"}]'::jsonb),
    ('isla-linen-lamp-shade','Isla Linen Lamp Shade','shades','lamp-shades',180, null,'A tapered natural-linen shade that gives table lamps a warm, softly diffused glow.','CL-ISLA','["Natural Linen"]'::jsonb,'[{"label":"Natural Linen","color":"#F0EBE0"},{"label":"Warm Sand","color":"#D8C7AD"}]'::jsonb),
    ('remy-marble-side-table','Remy Marble Side Table','tables','side-tables',760, null,'A pale marble top and fine metal base make an elegant perch for a lamp or a favourite object.','CL-REMY','["Natural Marble","Brass"]'::jsonb,'[{"label":"White Marble","color":"#E8E0D4"},{"label":"Grey Marble","color":"#9B8E82"}]'::jsonb),
    ('ellery-full-length-mirror','Ellery Full-Length Mirror','mirrors','full-length-mirrors',940, null,'A generous full-length mirror with a slim oak frame and a clean, timeless profile.','CL-ELLERY','["Oak Wood","Glass"]'::jsonb,'[{"label":"Natural Oak","color":"#C8A96E"},{"label":"Walnut","color":"#6B4B32"}]'::jsonb),
    ('marin-pleated-shade','Marin Pleated Shade','shades','lamp-shades',220, null,'A softly pleated cotton shade with a classic silhouette for a calm, layered interior.','CL-MARIN','["Cotton"]'::jsonb,'[{"label":"Ivory","color":"#F0EBE0"},{"label":"Oatmeal","color":"#D9C8B1"}]'::jsonb),
    ('luna-pendant','Luna Opal Pendant','lamps','pendant-lights',580, null,'A rounded opal-glass pendant diffuses an even, gentle light over dining tables and quiet corners.','CL-LUNA','["Glass","Brass"]'::jsonb,'[{"label":"Opal & Brass","color":"#F0EBE0"},{"label":"Opal & Black","color":"#3A3530"}]'::jsonb),
    ('mira-round-mirror','Mira Round Mirror','mirrors','wall-mirrors',520, null,'A round, polished-edge mirror that brings light and a calm focal point to any wall.','CL-MIRA','["Glass","Brass"]'::jsonb,'[{"label":"Brass","color":"#C9A362"},{"label":"Silver","color":"#9B8E82"}]'::jsonb),
    ('cole-nesting-tables','Cole Nesting Tables','tables','side-tables',640, null,'Two easy-to-move nesting tables add a useful surface beside a favourite chair or beneath a statement mirror.','CL-COLE','["Natural Ash","Walnut"]'::jsonb,'[{"label":"Natural Ash","color":"#D4B896"},{"label":"Walnut","color":"#6B4B32"}]'::jsonb),
    ('noor-velvet-shade','Noor Velvet Lamp Shade','shades','lamp-shades',260, null,'Soft velvet and a warm-toned lining give this tailored shade a rich finish and an inviting evening glow.','CL-NOOR','["Velvet"]'::jsonb,'[{"label":"Sage","color":"#8FA07E"},{"label":"Cocoa","color":"#6B4B32"}]'::jsonb)
)
insert into public.products(category_id, subcategory_id, name, slug, sku, description, price_bdt, compare_at_price_bdt, inventory_quantity, track_inventory, status, attributes, swatches, published_at)
select department.id, subcategory.id, seed.name, seed.slug, seed.sku, seed.description, seed.price_bdt, seed.compare_at_bdt, 10, true, 'active', jsonb_build_object('materials', seed.materials), seed.swatches, now()
from seed
join public.categories department on department.slug = seed.department and department.parent_id is null
join public.categories subcategory on subcategory.slug = seed.subcategory and subcategory.parent_id = department.id
on conflict (slug) do nothing;

with media(slug, image_url, role, sort_order) as (
  values
    ('marlow-table-lamp','https://images.unsplash.com/photo-1564540574859-0dfb63985953?auto=format&fit=crop&w=800&q=80','product',0),('marlow-table-lamp','https://images.unsplash.com/photo-1775667693473-91e07000bb1a?auto=format&fit=crop&w=800&q=80','lifestyle',1),
    ('solis-pendant','https://images.unsplash.com/photo-1775667693473-91e07000bb1a?auto=format&fit=crop&w=800&q=80','product',0),('solis-pendant','https://images.unsplash.com/photo-1778880707611-d1f09e32b4e2?auto=format&fit=crop&w=800&q=80','lifestyle',1),
    ('oslo-side-table','https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?auto=format&fit=crop&w=800&q=80','product',0),('oslo-side-table','https://images.unsplash.com/photo-1784651859128-b04c1d4732f3?auto=format&fit=crop&w=800&q=80','lifestyle',1),
    ('cleo-wall-sconce','https://images.unsplash.com/photo-1778880707611-d1f09e32b4e2?auto=format&fit=crop&w=800&q=80','product',0),('cleo-wall-sconce','https://images.unsplash.com/photo-1775667693473-91e07000bb1a?auto=format&fit=crop&w=800&q=80','lifestyle',1),
    ('milo-console-table','https://images.unsplash.com/photo-1784651859128-b04c1d4732f3?auto=format&fit=crop&w=800&q=80','product',0),('milo-console-table','https://images.unsplash.com/photo-1542485028-6e019f9c8a8e?auto=format&fit=crop&w=800&q=80','lifestyle',1),
    ('iris-dining-table','https://images.unsplash.com/photo-1784651859128-b04c1d4732f3?auto=format&fit=crop&w=800&q=80','product',0),('iris-dining-table','https://images.unsplash.com/photo-1775667693473-91e07000bb1a?auto=format&fit=crop&w=800&q=80','lifestyle',1),
    ('nora-table-lamp','https://images.unsplash.com/photo-1564540574859-0dfb63985953?auto=format&fit=crop&w=800&q=80','product',0),('nora-table-lamp','https://images.unsplash.com/photo-1780140765084-88e4e0d75528?auto=format&fit=crop&w=800&q=80','lifestyle',1),
    ('arc-floor-lamp','https://images.unsplash.com/photo-1778880707611-d1f09e32b4e2?auto=format&fit=crop&w=800&q=80','product',0),('arc-floor-lamp','https://images.unsplash.com/photo-1775667693473-91e07000bb1a?auto=format&fit=crop&w=800&q=80','lifestyle',1),
    ('solene-wall-mirror','https://images.unsplash.com/photo-1542485028-6e019f9c8a8e?auto=format&fit=crop&w=800&q=80','product',0),('solene-wall-mirror','https://images.unsplash.com/photo-1774428571582-9bd41e95a6ca?auto=format&fit=crop&w=800&q=80','lifestyle',1),
    ('isla-linen-lamp-shade','https://images.unsplash.com/photo-1774444052266-2e4b58d85c3b?auto=format&fit=crop&w=800&q=80','product',0),('isla-linen-lamp-shade','https://images.unsplash.com/photo-1564540574859-0dfb63985953?auto=format&fit=crop&w=800&q=80','lifestyle',1),
    ('remy-marble-side-table','https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?auto=format&fit=crop&w=800&q=80','product',0),('remy-marble-side-table','https://images.unsplash.com/photo-1784651859128-b04c1d4732f3?auto=format&fit=crop&w=800&q=80','lifestyle',1),
    ('ellery-full-length-mirror','https://images.unsplash.com/photo-1774428571582-9bd41e95a6ca?auto=format&fit=crop&w=800&q=80','product',0),('ellery-full-length-mirror','https://images.unsplash.com/photo-1542485028-6e019f9c8a8e?auto=format&fit=crop&w=800&q=80','lifestyle',1),
    ('marin-pleated-shade','https://images.unsplash.com/photo-1774444052266-2e4b58d85c3b?auto=format&fit=crop&w=800&q=80','product',0),('marin-pleated-shade','https://images.unsplash.com/photo-1778880707611-d1f09e32b4e2?auto=format&fit=crop&w=800&q=80','lifestyle',1),
    ('luna-pendant','https://images.unsplash.com/photo-1775667693473-91e07000bb1a?auto=format&fit=crop&w=800&q=80','product',0),('luna-pendant','https://images.unsplash.com/photo-1778880707611-d1f09e32b4e2?auto=format&fit=crop&w=800&q=80','lifestyle',1),
    ('mira-round-mirror','https://images.unsplash.com/photo-1542485028-6e019f9c8a8e?auto=format&fit=crop&w=800&q=80','product',0),('mira-round-mirror','https://images.unsplash.com/photo-1774428571582-9bd41e95a6ca?auto=format&fit=crop&w=800&q=80','lifestyle',1),
    ('cole-nesting-tables','https://images.unsplash.com/photo-1784651859128-b04c1d4732f3?auto=format&fit=crop&w=800&q=80','product',0),('cole-nesting-tables','https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?auto=format&fit=crop&w=800&q=80','lifestyle',1),
    ('noor-velvet-shade','https://images.unsplash.com/photo-1774444052266-2e4b58d85c3b?auto=format&fit=crop&w=800&q=80','product',0),('noor-velvet-shade','https://images.unsplash.com/photo-1564540574859-0dfb63985953?auto=format&fit=crop&w=800&q=80','lifestyle',1)
)
insert into public.product_images(product_id, public_url, alt_text, image_role, sort_order)
select products.id, media.image_url, products.name, media.role, media.sort_order
from media join public.products on products.slug = media.slug
where not exists (select 1 from public.product_images existing where existing.product_id = products.id and existing.public_url = media.image_url);
